/**:
  controller_manager:
    ros__parameters:
      update_rate: 20  # Hz

      cobot_arm_controller:
        type: "joint_trajectory_controller/JointTrajectoryController"

      end_effector_controller:
        type: "joint_trajectory_controller/JointTrajectoryController"

      joint_state_broadcaster:
        type: "joint_state_broadcaster/JointStateBroadcaster"

  cobot_arm_controller:
    ros__parameters:
      joints:
        - joint3_to_joint2
        - joint4_to_joint3
        - joint5_to_joint4
        - joint6_to_joint5
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true

  end_effector_controller:
    ros__parameters:
      joints:
        - joint6output_to_joint6
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
