controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    cobot_controller:
      type: cobot_controller/CobotController


cobot_controller:
  ros__parameters:
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
    expected_joints: 6.0


joint_state_broadcaster:
  ros__parameters: 
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
    interfaces:
      - position
      - velocity
