controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    cobot_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"


cobot_controller:
  ros__parameters:
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    interpolate_from_desired_state: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint1:
        trajectory: 0.05
        goal: 0.03

joint_state_broadcaster:
  ros__parameters: 
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
    interfaces:
      - position
      - velocity
